### ISSUE TITLE
[Preliminary Planning] Draw high level UML

### ISSUE THREAD

**Issue by Bnocz** [Bnocz/Panic-Building#17]
## Story
As a developer, I need to know how the entities in my project interact with each other.

## Specifications
- Draw a UML to show how each entity in the game interacts

## Acceptance
- [x] Have a UML diagram that specifies relationships between all classes.

**Comment by susansli** [comment]
![Image](https://github.com/user-attachments/assets/b639d3dc-285d-407f-8deb-d99fe6bcdc94)

**Comment by susansli** [comment]
@Bnocz did you look at why these issues are autoclosing yet?

**Comment by susansli** [comment]
@Bnocz I fixed it, just made a new status - maybe it has something to do with the default configs

**Comment by susansli** [comment]
@Bnocz can you document this? I did most of the actual design so I think that's a fair division of labor.
